name: PR review automation
on:
  pull_request_review:
    types: [submitted]

jobs:
  job:
    runs-on: ubuntu-latest
    steps: 
      - name: retrieve state
        run: |
          jq '.' $GITHUB_EVENT_PATH
          ACTION1=$(jq --raw-output ".action" $GITHUB_EVENT_PATH)
          echo "Label in action is $ACTION1"
          echo ::set-env name=ACTION::$ACTION
